name: Run OWASP Maven Dependency Check
on:
  workflow_call:
    inputs:
      runner-os:
        description: 'The OS to run the check on.'
        default: 'ubuntu-latest'
        required: false
        type: string
      java-distribution:
        description: 'The java distribution to run the check with.'
        default: 'temurin'
        required: false
        type: string
      java-version:
        description: 'The java version to run the check with.'
        default: 21
        required: false
        type: number
      check-command:
        description: 'The command used to generate the report.'
        default: 'mvn --s maven-settings.xml org.owasp:dependency-check-maven:12.1.6:check -DnvdValidForHours=24 -DfailBuildOnCVSS=0 -DsuppressionFile=suppression.xml -DnvdApiKeyEnvironmentVariable=NVD_API_KEY -DossIndexServerId=oss-index'
        required: false
        type: string
    secrets:
      nvd-api-key:
        description: 'The NVD API Key used to fetch the NVD database.'
        required: true
      ossindex-username:
        description: 'The OSS Index username to access the OSS Index database'
        required: false
      ossindex-token:
        description: 'The OSS Index API token to access the OSS Index database'
        required: false
      slack-webhook-url:
        description: 'The Slack webhook used for publishing the results.'
        required: true


jobs:
  check-dependencies:
    name: Check dependencies
    runs-on: ${{ inputs.runner-os }}
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          cache: 'maven'
      - name: Cache NVD DB
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data/
          key: dependency-check-${{ github.run_id }}
          restore-keys: |
            dependency-check
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 5
      - name: Override maven user settings
        run: |
          cat > maven-settings.xml << EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
              <localRepository/>
              <interactiveMode/>
              <offline/>
              <pluginGroups/>
              <servers>
                  <server>
                      <id>oss-index</id>
                      <username>\${env.OSSINDEX_USERNAME}</username>
                      <password>\${env.OSSINDEX_PASSWORD}</password>
                      <configuration></configuration>
                  </server>
              </servers>
              <mirrors/>
              <proxies/>
              <profiles/>
              <activeProfiles/>
          </settings>
          EOF
      - name: Run org.owasp:dependency-check plugin
        id: dependency-check
        continue-on-error: true
        run: ${{ inputs.check-command }}
        env:
          NVD_API_KEY: ${{ secrets.nvd-api-key }}
          OSSINDEX_USERNAME: ${{ secrets.ossindex-username }}
          OSSINDEX_PASSWORD: ${{ secrets.ossindex-token }}
      - name: Upload report on failure
        if: steps.dependency-check.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html
          if-no-files-found: error
      - name: Slack Notification on regular check
        if: github.event_name == 'schedule' && steps.dependency-check.outcome == 'failure'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.slack-webhook-url }}
          SLACK_USERNAME: 'Cryptobot'
          SLACK_ICON: false
          SLACK_ICON_EMOJI: ':bot:'
          SLACK_CHANNEL: 'cryptomator-desktop'
          SLACK_TITLE: "Vulnerabilities in ${{ github.event.repository.name }} detected."
          SLACK_MESSAGE: "Download the <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|report> for more details."
          SLACK_FOOTER: false
          MSG_MINIMAL: true
      - name: Failing workflow on release branch
        if: github.event_name == 'push' && steps.dependency-check.outcome == 'failure'
        shell: bash
        run: exit 1
